"""
Extracts one representative sensor window per HAR class from the processed dataset.
Finds the window closest to the class centroid (most "typical").
Outputs Dart constants for embedding in home_page.dart test functions.

Run from repo root:
  python scripts/extract_test_windows.py
"""
import numpy as np
from pathlib import Path
from scipy.signal import resample_poly, butter, filtfilt
from math import gcd

DATA_PROC = Path('data/processed')
DATA_RAW  = Path('data/raw')

# Load processed data (old label space: 1-6)
X        = np.load(DATA_PROC / 'X_activities.npy')       # (N, 128, 6)
y_raw    = np.load(DATA_PROC / 'y_activities.npy')        # 1-indexed
y_0      = y_raw - 1  # 0-indexed: 0=walk,1=up,2=down,3=sit,4=stand,5=run

# Old → canonical remapping
REMAP = {0: 1, 1: 4, 2: 5, 3: 0, 4: 0, 5: 2}
y_canonical = np.vectorize(REMAP.get)(y_0)

CLASS_NAMES = ['static', 'walking', 'running', 'cycling', 'upstairs', 'downstairs']

def centroid_window(X_class):
    """Return the window closest to the class mean (most representative)."""
    centroid = X_class.mean(axis=0)
    dists = np.mean((X_class - centroid) ** 2, axis=(1, 2))
    return X_class[np.argmin(dists)]

windows = {}

# Classes 0-2,4-5 from UCI+MotionSense
for canonical_idx, name in enumerate(CLASS_NAMES):
    if name == 'cycling':
        continue
    mask = y_canonical == canonical_idx
    if not mask.any():
        print(f'WARNING: no windows for {name}')
        continue
    w = centroid_window(X[mask])
    windows[name] = w
    print(f'{name}: {mask.sum()} windows, selected centroid window')

# Cycling from PAMAP2
def highpass_gravity_removal(accel_g, fs=50.0):
    b, a = butter(4, 0.3 / (fs / 2), btype='high')
    return filtfilt(b, a, accel_g, axis=0).astype(np.float32)

def resample_signal(data, orig_hz, target_hz=50):
    g = gcd(orig_hz, target_hz)
    return resample_poly(data, target_hz // g, orig_hz // g, axis=0).astype(np.float32)

pamap2_protocol = DATA_RAW / 'pamap2+physical+activity+monitoring' / 'PAMAP2_Dataset' / 'PAMAP2_Dataset' / 'Protocol'
cyc_windows = []
_ANKLE_ACCEL = [38, 39, 40]
_ANKLE_GYRO  = [44, 45, 46]

for dat_file in sorted(pamap2_protocol.glob('subject*.dat')):
    try:
        data = np.loadtxt(dat_file, dtype=np.float32)
    except Exception:
        continue
    mask = data[:, 1] == 6
    seg = data[mask]
    if len(seg) < 128:
        continue
    col_means = np.nanmean(seg, axis=0)
    nan_mask = np.isnan(seg)
    seg[nan_mask] = np.take(col_means, np.where(nan_mask)[1])

    accel_ms2 = resample_signal(seg[:, _ANKLE_ACCEL], 100, 50)
    gyro      = resample_signal(seg[:, _ANKLE_GYRO],  100, 50)
    n = min(len(accel_ms2), len(gyro))
    linear_g = highpass_gravity_removal(accel_ms2[:n] / 9.81)
    signal = np.concatenate([linear_g, gyro[:n]], axis=1).astype(np.float32)

    step = 64
    for s in range(0, len(signal) - 128 + 1, step):
        cyc_windows.append(signal[s:s+128])

if cyc_windows:
    X_cyc = np.stack(cyc_windows)
    windows['cycling'] = centroid_window(X_cyc)
    print(f'cycling: {len(cyc_windows)} windows from PAMAP2, selected centroid window')
else:
    print('WARNING: no cycling windows from PAMAP2')

# Output as Dart constants
def fmt_dart_list(w: np.ndarray, name: str) -> str:
    rows = []
    for row in w:
        vals = ', '.join(f'{v:.6f}' for v in row)
        rows.append(f'    [{vals}]')
    inner = ',\n'.join(rows)
    return f'// {name}\nconst List<List<double>> _kHar{name.capitalize()}Sample = [\n{inner}\n];'

output_lines = [
    '// Auto-generated by scripts/extract_test_windows.py',
    '// Real dataset windows for HAR model unit tests.',
    '// Each window: 128 samples × 6 channels [lax, lay, laz, gx, gy, gz]',
    '',
]

for name in CLASS_NAMES:
    if name in windows:
        output_lines.append(fmt_dart_list(windows[name], name))
        output_lines.append('')

dart_code = '\n'.join(output_lines)

out_path = Path('app/lib/inference/har_test_samples.dart')
out_path.write_text(dart_code, encoding='utf-8')
print(f'\nWritten to {out_path}')
print('Add this import to home_page.dart and use _kHar<Class>Sample in _testHar().')
